name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build
      run: |
        cl /O2 main.cpp d3d11.lib dxgi.lib d3dcompiler.lib user32.lib gdi32.lib /Fe:upscaler.exe

    - uses: actions/upload-artifact@v4
      with:
        name: upscaler
        path: upscaler.exe
