name: Build Scaler
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSVC to PATH
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile
        run: |
          cl.exe /O2 /MT /EHsc main.cpp /link d3d11.lib dxgi.lib d3dcompiler.lib user32.lib gdi32.lib /OUT:SharpScaler.exe
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SharpScaler-Binary
          path: SharpScaler.exe
